[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 5
minReplicas = 1

[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[services.whatsapp]
numReplicas = 1
memorySizeInMb = 512
healthcheckPath = "/health"
healthcheckTimeoutInSeconds = 3
healthcheckIntervalInSeconds = 30

[services.whatsapp.environment]
NODE_ENV = "production"
PORT = "3001"

# Configuración para mantener el servicio activo
[services.whatsapp.warmup]
enabled = true
concurrency = 1
intervalSeconds = 120