services:
  - type: web
    name: whatsapp-service
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept"

    autoDeploy: true